# Generated by Django 3.0.7 on 2020-06-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('object_to_attach_id', models.TextField()),
                ('author_id', models.IntegerField()),
                ('comment', models.TextField(max_length=140)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('author', models.TextField(max_length=50)),
                ('attach_object_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField()),
                ('img', models.ImageField(upload_to='post_pics')),
                ('description', models.TextField(default='', max_length=280)),
                ('likes', models.IntegerField(default=0)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('views_list', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField()),
                ('img', models.ImageField(upload_to='post_pics')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50, unique=True)),
                ('password', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('token', models.TextField(unique=True)),
            ],
        ),
    ]
