# Generated by Django 3.0.7 on 2020-06-30 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expier_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 15, 17, 10, 910856)),
        ),
    ]
